"""add realestate_projects + field labels

Revision ID: 3e77f4fa421a
Revises: d34a7f1cc9f4
Create Date: 2026-06-13 20:23:53.803463
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e77f4fa421a'
down_revision: Union[str, None] = 'd34a7f1cc9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realestate_project_field_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'kind', 'idx', name='uq_company_re_project_field')
    )
    with op.batch_alter_table('realestate_project_field_labels', schema=None) as batch_op:
        batch_op.create_index('ix_re_project_field_label_company', ['company_id'], unique=False)

    op.create_table('realestate_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_membership_id', sa.Integer(), nullable=True),
    sa.Column('project_number', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('param1', sa.String(length=500), nullable=True),
    sa.Column('param2', sa.String(length=500), nullable=True),
    sa.Column('param3', sa.String(length=500), nullable=True),
    sa.Column('param4', sa.String(length=500), nullable=True),
    sa.Column('param5', sa.String(length=500), nullable=True),
    sa.Column('param6', sa.String(length=500), nullable=True),
    sa.Column('param7', sa.String(length=500), nullable=True),
    sa.Column('param8', sa.String(length=500), nullable=True),
    sa.Column('param9', sa.String(length=500), nullable=True),
    sa.Column('param10', sa.String(length=500), nullable=True),
    sa.Column('param11', sa.String(length=500), nullable=True),
    sa.Column('param12', sa.String(length=500), nullable=True),
    sa.Column('param13', sa.String(length=500), nullable=True),
    sa.Column('param14', sa.String(length=500), nullable=True),
    sa.Column('param15', sa.String(length=500), nullable=True),
    sa.Column('num1', sa.Float(), nullable=True),
    sa.Column('num2', sa.Float(), nullable=True),
    sa.Column('num3', sa.Float(), nullable=True),
    sa.Column('num4', sa.Float(), nullable=True),
    sa.Column('num5', sa.Float(), nullable=True),
    sa.Column('num6', sa.Float(), nullable=True),
    sa.Column('num7', sa.Float(), nullable=True),
    sa.Column('num8', sa.Float(), nullable=True),
    sa.Column('num9', sa.Float(), nullable=True),
    sa.Column('num10', sa.Float(), nullable=True),
    sa.Column('num11', sa.Float(), nullable=True),
    sa.Column('num12', sa.Float(), nullable=True),
    sa.Column('num13', sa.Float(), nullable=True),
    sa.Column('num14', sa.Float(), nullable=True),
    sa.Column('num15', sa.Float(), nullable=True),
    sa.Column('flag1', sa.Boolean(), nullable=False),
    sa.Column('flag2', sa.Boolean(), nullable=False),
    sa.Column('flag3', sa.Boolean(), nullable=False),
    sa.Column('flag4', sa.Boolean(), nullable=False),
    sa.Column('flag5', sa.Boolean(), nullable=False),
    sa.Column('list1', sa.String(length=500), nullable=True),
    sa.Column('list2', sa.String(length=500), nullable=True),
    sa.Column('list3', sa.String(length=500), nullable=True),
    sa.Column('list4', sa.String(length=500), nullable=True),
    sa.Column('list5', sa.String(length=500), nullable=True),
    sa.Column('list6', sa.String(length=500), nullable=True),
    sa.Column('list7', sa.String(length=500), nullable=True),
    sa.Column('list8', sa.String(length=500), nullable=True),
    sa.Column('list9', sa.String(length=500), nullable=True),
    sa.Column('list10', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_membership_id'], ['customer_companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('realestate_projects', schema=None) as batch_op:
        batch_op.create_index('ix_realestate_projects_company', ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realestate_projects', schema=None) as batch_op:
        batch_op.drop_index('ix_realestate_projects_company')

    op.drop_table('realestate_projects')
    with op.batch_alter_table('realestate_project_field_labels', schema=None) as batch_op:
        batch_op.drop_index('ix_re_project_field_label_company')

    op.drop_table('realestate_project_field_labels')
    # ### end Alembic commands ###
