"""initial schema

Revision ID: 4650176fd531
Revises: 
Create Date: 2026-06-05 11:38:03.708350
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4650176fd531'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('national_id', sa.String(length=40), nullable=True),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_email', ['email'], unique=False)
        batch_op.create_index('ix_customers_national_id', ['national_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('ix_api_keys_company', ['company_id'], unique=False)
        batch_op.create_index('ix_api_keys_hash', ['key_hash'], unique=False)

    op.create_table('customer_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('parent_membership_id', sa.Integer(), nullable=True),
    sa.Column('is_paying', sa.Boolean(), nullable=False),
    sa.Column('paid_by_membership_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_membership_id'], ['customer_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_membership_id'], ['customer_companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'customer_id', name='uq_company_customer')
    )
    with op.batch_alter_table('customer_companies', schema=None) as batch_op:
        batch_op.create_index('ix_cc_company', ['company_id'], unique=False)
        batch_op.create_index('ix_cc_customer', ['customer_id'], unique=False)

    op.create_table('field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_company_field_key')
    )
    with op.batch_alter_table('field_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_fd_company', ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_company', ['company_id'], unique=False)

    op.create_table('customer_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['customer_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'field_definition_id', name='uq_membership_field')
    )
    with op.batch_alter_table('customer_field_values', schema=None) as batch_op:
        batch_op.create_index('ix_cfv_membership', ['membership_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_field_values', schema=None) as batch_op:
        batch_op.drop_index('ix_cfv_membership')

    op.drop_table('customer_field_values')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_company')

    op.drop_table('users')
    with op.batch_alter_table('field_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_fd_company')

    op.drop_table('field_definitions')
    with op.batch_alter_table('customer_companies', schema=None) as batch_op:
        batch_op.drop_index('ix_cc_customer')
        batch_op.drop_index('ix_cc_company')

    op.drop_table('customer_companies')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_api_keys_hash')
        batch_op.drop_index('ix_api_keys_company')

    op.drop_table('api_keys')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_national_id')
        batch_op.drop_index('ix_customers_email')

    op.drop_table('customers')
    op.drop_table('companies')
    # ### end Alembic commands ###
