"""priority sync: connection + field map

Revision ID: 511ad36776a1
Revises: a1b2c3d4e5f6
Create Date: 2026-06-13 09:09:50.133116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511ad36776a1'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('entity_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_msg', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_priority_conn_company')
    )
    op.create_table('priority_field_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('priority_field', sa.String(length=120), nullable=False),
    sa.Column('priority_label', sa.String(length=200), nullable=True),
    sa.Column('priority_type', sa.String(length=80), nullable=True),
    sa.Column('target_field', sa.String(length=80), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'priority_field', name='uq_priority_map_field')
    )
    with op.batch_alter_table('priority_field_maps', schema=None) as batch_op:
        batch_op.create_index('ix_priority_map_company', ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority_field_maps', schema=None) as batch_op:
        batch_op.drop_index('ix_priority_map_company')

    op.drop_table('priority_field_maps')
    op.drop_table('priority_connections')
    # ### end Alembic commands ###
