"""customer spec fields

Revision ID: 7b2fb0285563
Revises: 4650176fd531
Create Date: 2026-06-05 12:19:03.645703
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2fb0285563'
down_revision: Union[str, None] = '4650176fd531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('street1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city1', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('street2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city2', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('param1', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param3', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param4', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param5', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param6', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param7', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param8', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param9', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('param10', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint('uq_customers_customer_number', ['customer_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customers_customer_number', type_='unique')
        batch_op.drop_column('param10')
        batch_op.drop_column('param9')
        batch_op.drop_column('param8')
        batch_op.drop_column('param7')
        batch_op.drop_column('param6')
        batch_op.drop_column('param5')
        batch_op.drop_column('param4')
        batch_op.drop_column('param3')
        batch_op.drop_column('param2')
        batch_op.drop_column('param1')
        batch_op.drop_column('city2')
        batch_op.drop_column('street2')
        batch_op.drop_column('city1')
        batch_op.drop_column('street1')
        batch_op.drop_column('nickname')
        batch_op.drop_column('customer_number')

    # ### end Alembic commands ###
