"""param_labels table

Revision ID: 9238e5ad5c1a
Revises: 92fcba3dabcf
Create Date: 2026-06-12 22:29:06.753926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9238e5ad5c1a'
down_revision: Union[str, None] = '92fcba3dabcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('param_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('param_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'param_index', name='uq_company_param_index')
    )
    with op.batch_alter_table('param_labels', schema=None) as batch_op:
        batch_op.create_index('ix_param_label_company', ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('param_labels', schema=None) as batch_op:
        batch_op.drop_index('ix_param_label_company')

    op.drop_table('param_labels')
    # ### end Alembic commands ###
