"""role_options table

Revision ID: 92fcba3dabcf
Revises: ff827e7cdc13
Create Date: 2026-06-12 21:47:37.565607
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fcba3dabcf'
down_revision: Union[str, None] = 'ff827e7cdc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'label', name='uq_company_role_option')
    )
    with op.batch_alter_table('role_options', schema=None) as batch_op:
        batch_op.create_index('ix_role_option_company', ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_options', schema=None) as batch_op:
        batch_op.drop_index('ix_role_option_company')

    op.drop_table('role_options')
    # ### end Alembic commands ###
