"""customer: company_name, allow_mailing, customer_links; drop parent

Revision ID: c9fb3bb2bb1e
Revises: 7b2fb0285563
Create Date: 2026-06-12 19:15:15.880203
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fb3bb2bb1e'
down_revision: Union[str, None] = '7b2fb0285563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('linked_membership_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['linked_membership_id'], ['customer_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['customer_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'linked_membership_id', name='uq_customer_link')
    )
    with op.batch_alter_table('customer_links', schema=None) as batch_op:
        batch_op.create_index('ix_clink_membership', ['membership_id'], unique=False)

    # Batch mode rebuilds the table without this column, dropping its FK too.
    with op.batch_alter_table('customer_companies', schema=None) as batch_op:
        batch_op.drop_column('parent_membership_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))
        # server_default so the NOT NULL column populates existing rows on upgrade.
        batch_op.add_column(sa.Column('allow_mailing', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('allow_mailing')
        batch_op.drop_column('company_name')

    with op.batch_alter_table('customer_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_membership_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'customer_companies', ['parent_membership_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('customer_links', schema=None) as batch_op:
        batch_op.drop_index('ix_clink_membership')

    op.drop_table('customer_links')
    # ### end Alembic commands ###
