"""add editable creation_date to customers and projects

Revision ID: d34a7f1cc9f4
Revises: 511ad36776a1
Create Date: 2026-06-13 11:03:36.237304
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34a7f1cc9f4'
down_revision: Union[str, None] = '511ad36776a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.Date(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
